# Generated by Django 3.2 on 2021-04-28 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('GB', 'GLOBAL'), ('NH', 'NORTHER_HEMISPHERE'), ('SH', 'SOUTHERN_HEMISPHERE')], default='GB', max_length=2)),
                ('surface_type', models.CharField(choices=[('LD', 'LAND'), ('WT', 'WATER'), ('LW', 'LAND_AND_WATER')], default='LW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
        ),
    ]
